### ISSUE TITLE
Working outside AWS

### ISSUE THREAD

**Issue by bsridatta** [outerbounds/metaflowbot#7]
Should the metadata be always hosted on AWS? As the aws url is required. Or can it be any url?

**Comment by valayDave** [comment]
You can setup a metadata server anywhere. You just need a URL to this server. If have not attached a domain to the server, you can even use the IP address for that server. This address needs to be present in the [configuration variables](https://github.com/outerbounds/metaflowbot/blob/main/docs/deployment.md#locally-via-a-docker-image) (If deploying bot via docker) or the [config file](https://outerbounds.com/docs/configure-metaflow) (if running the bot [locally via pip](https://github.com/outerbounds/metaflowbot/blob/main/docs/deployment.md#locally-with-pip)).

**Comment by bsridatta** [comment]
Thats great, thanks for the quick response
